module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e1e3e5",
        "surface-tint": "#c0000c",
        "on-primary": "#ffffff",
        "outline": "#936e69",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#444747",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#191c1c",
        "secondary-fixed-dim": "#c5c7c9",
        "background": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#930007",
        "inverse-primary": "#ffb4aa",
        "surface-dim": "#d9dadb",
        "on-background": "#191c1d",
        "on-secondary-fixed": "#191c1e",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e4",
        "error": "#ba1a1a",
        "tertiary-container": "#6f7271",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#410001",
        "on-primary-container": "#fff5f3",
        "secondary": "#5c5f61",
        "tertiary-fixed-dim": "#c5c7c6",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#626567",
        "tertiary": "#565a59",
        "tertiary-fixed": "#e1e3e1",
        "secondary-container": "#e1e3e5",
        "primary": "#b5000b",
        "inverse-on-surface": "#f0f1f2",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#ffb4aa",
        "on-surface-variant": "#5e3f3b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#444749",
        "on-tertiary-container": "#f6f8f6",
        "surface": "#f8f9fa",
        "primary-fixed": "#ffdad5",
        "primary-container": "#e30613",
        "outline-variant": "#e9bcb6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "8px",
        "base": "4px",
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "lg": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "data-mono": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
